import { Callout } from 'nextra/components'

# Mobile API

The Mobile API provides all necessary endpoints for user discovery, authentication, ticket synchronization, custom accessibility-focused pedestrian navigation, and real-time interactive mapping inside the Lattice mobile application.

---

## 1. Authentication and User Profiles

Routes associated with identity management, profile retrieval, and accessibility-specific navigation preferences.

### Local Registration

Initializes a new user account, registers credentials, and returns the active session token along with associated ticket objects.

- **Route**: `POST /auth/register`
- **Headers**: `Content-Type: application/json`
- **Request Body**:
  ```json
  {
    "email": "user@example.com",
    "password": "secure_password_123",
    "fullName": "Alejandro Perez",
    "ticket_code": "TCK-12345-XYZ"
  }
  ```
- **Response (201 Created)**:
  ```json
  {
    "user": {
      "id": 42,
      "email": "user@example.com",
      "fullName": "Alejandro Perez",
      "hasTicket": true
    },
    "token": "eyJhbGciOiJIUzI1NiIsIn...",
    "tickets": [
      {
        "id": 10,
        "code": "TCK-12345-XYZ",
        "gate": "Gate 3",
        "zoneName": "Grandstand G",
        "seatRow": "12",
        "seatNumber": "4"
      }
    ]
  }
  ```

### Local Login

Authenticates an existing user utilizing email and password credentials.

- **Route**: `POST /auth/login`
- **Request Body**:
  ```json
  {
    "email": "user@example.com",
    "password": "secure_password_123"
  }
  ```
- **Response (200 OK)**:
  ```json
  {
    "user": {
      "id": 42,
      "email": "user@example.com",
      "fullName": "Alejandro Perez",
      "hasTicket": true
    },
    "token": "eyJhbGciOiJIUzI1NiIsIn...",
    "tickets": [...]
  }
  ```

### Social Authentication: Google

Registers or logs in a user using an identity credential token issued by Google OAuth services.

- **Route**: `POST /auth/google`
- **Request Body**:
  ```json
  {
    "token": "google_identity_credential_jwt_token",
    "ticket_code": "TCK-999-MNO"
  }
  ```
- **Response (200 OK)**:
  ```json
  {
    "user": {
      "id": 45,
      "email": "user.google@gmail.com",
      "fullName": "Google User",
      "hasTicket": true,
      "avatarUrl": "https://lh3.googleusercontent.com/..."
    },
    "token": "eyJhbGciOiJIUzI1NiIsIn..."
  }
  ```

### Social Authentication: Apple

Registers or logs in a user utilizing an Apple-issued identity token.

- **Route**: `POST /auth/apple`
- **Request Body**:
  ```json
  {
    "token": "apple_identity_token_string",
    "fullName": {
      "firstName": "Oriol",
      "lastName": "Vila"
    },
    "ticket_code": "TCK-999-MNO"
  }
  ```
- **Response (200 OK)**:
  ```json
  {
    "user": {
      "id": 46,
      "email": "apple_user@example.com",
      "fullName": "Oriol Vila",
      "hasTicket": true,
      "avatarUrl": null
    },
    "token": "eyJhbGciOiJIUzI1NiIsIn..."
  }
  ```

### Biometric Authentication (Passkeys)

The platform supports the WebAuthn standard for secure, passwordless biometric logins.

#### Passkey Registration (Phase 1 - Challenge)
Generates client-specific challenge options requested by the biometric hardware.
- **Route**: `POST /auth/passkey/register-challenge`
- **Security**: Requires Bearer authentication
- **Response (200 OK)**:
  ```json
  {
    "challenge": "mock_registration_challenge",
    "rp": { "name": "Lattice", "id": "lattice.dev" },
    "user": { "id": "user_123", "name": "user@example.com", "displayName": "Alejandro Perez" },
    "pubKeyCredParams": [{ "alg": -7, "type": "public-key" }]
  }
  ```

#### Passkey Registration (Phase 2 - Verification)
Validates and persists the public key credential generated by the user's hardware device.
- **Route**: `POST /auth/passkey/register-verify`
- **Security**: Requires Bearer authentication
- **Request Body**:
  ```json
  {
    "id": "generated_credential_id",
    "response": {
      "clientDataJSON": "...",
      "attestationObject": "..."
    }
  }
  ```
- **Response (200 OK)**:
  ```json
  { "success": true }
  ```

#### Passkey Login (Phase 1 - Challenge)
Obtains an authentication challenge for validating a registered passkey.
- **Route**: `GET /auth/passkey/login-challenge`
- **Response (200 OK)**:
  ```json
  {
    "challenge": "mock_login_challenge",
    "allowCredentials": []
  }
  ```

#### Passkey Login (Phase 2 - Verification)
Verifies the cryptographic signature submitted by the hardware device and signs a session JWT.
- **Route**: `POST /auth/passkey/login-verify`
- **Request Body**:
  ```json
  {
    "id": "generated_credential_id",
    "response": {
      "clientDataJSON": "...",
      "authenticatorData": "...",
      "signature": "..."
    }
  }
  ```
- **Response (200 OK)**:
  ```json
  {
    "user": { "id": 42, "email": "user@example.com", "fullName": "Alejandro Perez" },
    "token": "eyJhbGciOiJIUzI1NiIsIn..."
  }
  ```

### Get Authenticated User Profile

Retrieves profile data and current accessibility settings for the active session.

- **Route**: `GET /auth/me`
- **Security**: Requires Bearer authentication
- **Response (200 OK)**:
  ```json
  {
    "id": 42,
    "email": "user@example.com",
    "fullName": "Alejandro Perez",
    "hasTicket": true,
    "avoidStairs": false,
    "avoidCrowds": true,
    "avoidSlopes": false,
    "avoidGrandstands": false,
    "isPasskeyEnabled": true,
    "avatarUrl": "https://..."
  }
  ```

### Update Accessibility Preferences

Updates pedestrian navigation constraints and preferences inside the user's profile to customize route generation.

- **Route**: `PATCH /auth/me`
- **Security**: Requires Bearer authentication
- **Request Body**:
  ```json
  {
    "avoidStairs": true,
    "avoidCrowds": false,
    "avoidSlopes": true,
    "fullName": "Alejandro Perez Modified"
  }
  ```
- **Response (200 OK)**:
  ```json
  {
    "id": 42,
    "email": "user@example.com",
    "fullName": "Alejandro Perez Modified",
    "hasTicket": true,
    "avoidStairs": true,
    "avoidCrowds": false,
    "avoidSlopes": true,
    "avoidGrandstands": false,
    "avatarUrl": "https://..."
  }
  ```

---

## 2. Ticket Management

Endpoints dedicated to claiming, unclaiming, and synchronizing physical and digital event tickets.

### Claim Ticket

Associates an active ticket code with the current user's profile.

- **Route**: `POST /auth/ticket/claim`
- **Security**: Requires Bearer authentication
- **Request Body**:
  ```json
  {
    "ticket_code": "TCK-12345-XYZ"
  }
  ```
- **Response (200 OK)**:
  ```json
  {
    "success": true,
    "message": "Ticket claimed successfully",
    "ticket_info": {
      "id": 10,
      "code": "TCK-12345-XYZ",
      "userId": 42,
      "gate": "Gate 3",
      "zoneName": "Grandstand G",
      "seatRow": "12",
      "seatNumber": "4"
    },
    "tickets": [...]
  }
  ```

### Unclaim Ticket

Removes the association between a ticket code and the current user's profile.

- **Route**: `POST /auth/ticket/unclaim`
- **Security**: Requires Bearer authentication
- **Request Body**:
  ```json
  {
    "ticket_code": "TCK-12345-XYZ"
  }
  ```
- **Response (200 OK)**:
  ```json
  {
    "success": true,
    "message": "Ticket removed successfully",
    "tickets": []
  }
  ```

### Retrieve User Tickets

Lists all claimed tickets associated with the active user account.

- **Route**: `GET /auth/tickets`
- **Security**: Requires Bearer authentication
- **Response (200 OK)**:
  ```json
  [
    {
      "id": 10,
      "code": "TCK-12345-XYZ",
      "gate": "Gate 3",
      "zoneName": "Grandstand G",
      "seatRow": "12",
      "seatNumber": "4",
      "isActive": true
    }
  ]
  ```

### Express QR Ticket Synchronization

Scans ticket data to automatically provision a guest user account or directly bind a ticket without stepping through standard local registration flows first.

- **Route**: `POST /auth/ticket-sync`
- **Request Body**:
  ```json
  {
    "qr_code_data": "{\"code\":\"TCK-12345-XYZ\",\"email\":\"guest@example.com\"}"
  }
  ```
- **Response (200 OK)**:
  ```json
  {
    "user": {
      "id": 48,
      "email": "guest@example.com",
      "fullName": "guest",
      "hasTicket": true
    },
    "token": "eyJhbGciOiJIUzI1NiIsIn...",
    "ticket_info": {
      "gate": "Gate 3",
      "zoneName": "Grandstand G",
      "seatRow": "12",
      "seatNumber": "4",
      "seatLocation": [2.2645, 41.5701]
    },
    "tickets": [...],
    "requires_setup": true
  }
  ```

---

## 3. Discovery and Geospatial Feeds

Routes used to populate mapping interfaces and localized feed systems.

### List Available Events

Obtains a list of all urban events, festivals, and permanent geographic layouts.

- **Route**: `GET /events`
- **Response (200 OK)**:
  ```json
  [
    {
      "id": 1,
      "name": "Forum Music Festival",
      "type": "music",
      "locationName": "Parc del Forum",
      "address": "Placa del Forum, 1, Barcelona",
      "startDate": "2026-05-20T12:00:00.000Z",
      "endDate": "2026-05-22T23:59:00.000Z",
      "isPermanent": false,
      "primaryColor": "#5856D6",
      "center": {
        "type": "Point",
        "coordinates": [2.2223, 41.4121]
      },
      "boundary": {
        "type": "Polygon",
        "coordinates": [...]
      },
      "bannerUrl": "https://...",
      "galleryUrls": ["https://...", "https://..."],
      "icon_name": "event",
      "color_hex": "#5856D6",
      "display_name": "Forum Music Festival"
    }
  ]
  ```

### Get Event Details

Retrieves comprehensive metadata for a specific event by ID. Triggers an asynchronous social metric synchronization in the background if social statistics are missing.

- **Route**: `GET /events/:id`
- **Response (200 OK)**:
  ```json
  {
    "id": 1,
    "name": "Forum Music Festival",
    "description": "The most vibrant music festival in front of the Mediterranean Sea.",
    "type": "music",
    "locationName": "Parc del Forum",
    "address": "Placa del Forum, 1, Barcelona",
    "startDate": "2026-05-20T12:00:00.000Z",
    "endDate": "2026-05-22T23:59:00.000Z",
    "isPermanent": false,
    "primaryColor": "#5856D6",
    "center": {
      "type": "Point",
      "coordinates": [2.2223, 41.4121]
    },
    "boundary": {
      "type": "Polygon",
      "coordinates": [...]
    },
    "bannerUrl": "https://...",
    "galleryUrls": [...],
    "metadata": {
      "social": {
        "likes": 1240,
        "shares": 348
      }
    },
    "icon_name": "event",
    "color_hex": "#5856D6",
    "display_name": "Forum Music Festival"
  }
  ```

### Get Event Perimeter and POIs (Spatial Data)

Fetches the polygon boundaries and inner Points of Interest for an event in a single optimized spatial database query backed by Redis caching.

- **Route**: `GET /events/:id/spatial`
- **Response (200 OK)**:
  ```json
  {
    "boundary": {
      "type": "Polygon",
      "coordinates": [...]
    },
    "pois": [
      {
        "id": 5,
        "name": "Main Entrance",
        "type": "entrance",
        "location": {
          "type": "Point",
          "coordinates": [2.2215, 41.4118]
        },
        "status": "open",
        "crowdLevel": "low"
      }
    ]
  }
  ```

### Get Event Brand Configuration

Obtains custom branding properties and layout configurations for styling the mobile UI based on the targeted event.

- **Route**: `GET /auth/event-config/:eventId`
- **Response (200 OK)**:
  ```json
  {
    "id": 1,
    "name": "Forum Music Festival",
    "primaryColor": "#5856D6",
    "bannerUrl": "https://...",
    "isPermanent": false
  }
  ```

### List Points of Interest (POIs)

Retrieves all registered POIs, supporting category and event-level filtering.

- **Route**: `GET /pois`
- **Query Parameters**:
  - `category` (optional): Filter by POI type (e.g., `restaurant`, `wc`, `gate`, `medical`).
  - `eventId` (optional): Filter by the parent event ID container.
- **Response (200 OK)**:
  ```json
  [
    {
      "id": 5,
      "eventId": 1,
      "name": "Food Court A",
      "description": "A wide variety of local and vegan options.",
      "type": "restaurant",
      "location": {
        "type": "Point",
        "coordinates": [2.2231, 41.4125]
      },
      "status": "open",
      "crowdLevel": "moderate",
      "capacity": 200,
      "isWheelchairAccessible": true,
      "hasPriorityLane": true
    }
  ]
  ```

### POI Categories

Returns the static master list of supported POI categories and their recommended Icon mappings for map renderings.

- **Route**: `GET /pois/categories`
- **Response (200 OK)**:
  ```json
  [
    { "id": "1", "label": "Access Points", "icon": "log-in", "category": "gate" },
    { "id": "2", "label": "Grandstands", "icon": "map", "category": "grandstand" },
    { "id": "3", "label": "Gastronomy", "icon": "coffee", "category": "restaurant" },
    { "id": "6", "label": "Restrooms", "icon": "user", "category": "wc" },
    { "id": "7", "label": "Medical", "icon": "plus-square", "category": "medical" }
  ]
  ```

### Contextual Discovery Feed

Fetches location-aware updates and discovery feeds based on geographic coordinates.

- **Route**: `GET /discovery`
- **Query Parameters**:
  - `lat` (optional): Latitude coordinate.
  - `lng` (optional): Longitude coordinate.
- **Response (200 OK)**:
  ```json
  {
    "nearbyEvents": [...],
    "trendingLocations": [...],
    "personalizedAlerts": []
  }
  ```

---

## 4. Navigation and Routing

Routing engines that calculate pedestrian trails modified by personal accessibility triggers.

### Get Standard Accessible Route

Generates the optimal path connecting two coordinates utilizing internal event paths and respecting specific accessibility flags.

- **Route**: `POST /navigation/route`
- **Request Body**:
  ```json
  {
    "origin": [2.2215, 41.4118],
    "destination": [2.2231, 41.4125],
    "avoidStairs": true,
    "wheelchairAccess": true,
    "eventId": 1
  }
  ```
- **Response (200 OK)**:
  ```json
  {
    "distanceMeters": 185.4,
    "durationSeconds": 142.0,
    "avoidedStairs": true,
    "geometry": {
      "type": "LineString",
      "coordinates": [
        [2.2215, 41.4118],
        [2.2221, 41.4121],
        [2.2231, 41.4125]
      ]
    },
    "waypoints": [...]
  }
  ```

### Valhalla External Route Proxy

Queries the external Valhalla mapping engine for long-distance routes outside the pre-mapped event boundaries.

- **Route**: `POST /navigation/valhalla-route`
- **Request Body**:
  ```json
  {
    "origin": [2.1734, 41.3851],
    "destination": [2.1901, 41.3923],
    "mode": "walking",
    "avoidStairs": true
  }
  ```
- **Response (200 OK)**:
  ```json
  {
    "trip": {
      "locations": [...],
      "legs": [
        {
          "shape": "g_opFsqyHgC...",
          "summary": {
            "length": 1.84,
            "time": 1324
          }
        }
      ]
    }
  }
  ```

### Forward Geocoding (Resolve Address)

Translates textual addresses into precise coordinate points for routing setups.

- **Route**: `GET /resolve-address`
- **Query Parameters**:
  - `address`: The textual address query (e.g., "Parc del Forum, Barcelona").
- **Response (200 OK)**:
  ```json
  {
    "address": "Parc del Forum, Barcelona, Catalonia",
    "location": {
      "type": "Point",
      "coordinates": [2.2223, 41.4121]
    }
  }
  ```

---

## 5. Saved Locations

Protected user routes for managing personal pins on map canvases.

### List Saved Locations

Fetches all saved locations associated with the authenticated account, returned as a standard GeoJSON FeatureCollection.

- **Route**: `GET /saved`
- **Security**: Requires Bearer authentication
- **Response (200 OK)**:
  ```json
  {
    "type": "FeatureCollection",
    "features": [
      {
        "type": "Feature",
        "geometry": {
          "type": "Point",
          "coordinates": [2.2235, 41.4129]
        },
        "properties": {
          "id": 1,
          "label": "Family Reunion Point",
          "createdAt": "2026-05-18T12:00:00.000Z"
        }
      }
    ]
  }
  ```

### Save New Location

Persists a new coordinate point with a descriptive label to the user's profile.

- **Route**: `POST /saved`
- **Security**: Requires Bearer authentication
- **Request Body**:
  ```json
  {
    "label": "Family Reunion Point",
    "latitude": 41.4129,
    "longitude": 2.2235
  }
  ```
- **Response (201 Created)**:
  ```json
  {
    "id": 1,
    "userId": 42,
    "label": "Family Reunion Point",
    "createdAt": "2026-05-18T12:00:00.000Z"
  }
  ```

### Delete Saved Location

Removes a saved coordinate pin by its unique ID.

- **Route**: `DELETE /saved/:id`
- **Security**: Requires Bearer authentication
- **Response (204 No Content)**:
  *(Empty body)*

---

## 6. Live Telemetry and Social Sharing

Real-time geographic reporting models for crowd monitoring and peer tracking.

### Post Device Location (Ping)

Pings the server with current device coordinates to feeds crowd monitoring models for an active event.

- **Route**: `POST /telemetry/ping`
- **Request Body**:
  ```json
  {
    "userId": 42,
    "eventId": 1,
    "latitude": 41.4121,
    "longitude": 2.2223
  }
  ```
- **Response (201 Created)**:
  ```json
  {
    "status": "ok"
  }
  ```

### Query Active Crowd Heatmap

Obtains active device pings received within the last 2 minutes for a specific event, pre-formatted as a GeoJSON FeatureCollection ready for immediate MapLibre Heatmap layer rendering.

- **Route**: `GET /telemetry/heatmap/:eventId`
- **Response (200 OK)**:
  ```json
  {
    "type": "FeatureCollection",
    "features": [
      {
        "type": "Feature",
        "properties": {
          "id": 254
        },
        "geometry": {
          "type": "Point",
          "coordinates": [2.2223, 41.4121]
        }
      }
    ]
  }
  ```

### Initialize Social Tracking Group

Registers a temporary shared group for real-time multiplayer location tracking.

- **Route**: `POST /groups`
- **Request Body**:
  ```json
  {
    "name": "Festival Crew",
    "members": ["user_123", "user_456"]
  }
  ```
- **Response (200 OK)**:
  ```json
  {
    "message": "Groups endpoint not implemented yet"
  }
  ```
